composer.autoloader_path: server/vendor/autoload.php

code_transform.class_new.variants:
  final: final
  "PHPUnit test": phpunit_test

navigator.destinations:
    source: server/src/<kernel>.php
    "PHPUnit test": server/tests/<kernel>Test.php

navigator.autocreate:
  source: final
  "PHPUnit test": "PHPUnit test"
