# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            EventSauce\EventSourcing\AggregateRootRepository $identityUserRepository: "@identity_user_event_repository"



    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Ui\Api\:
        resource: '../src/Ui/Api'
        tags: ['controller.service_arguments']


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # the following EventSauce rules set up the persistence of events
    identity_user_event_repository:
        class: EventSauce\EventSourcing\ConstructingAggregateRootRepository
        arguments:
            - "App\\Domain\\Identity\\User"
            - "@identity_user_message_repository"
            - "@App\\Infrastructure\\Shared\\Event\\MessengerComponentMessageDispatcher"

    identity_user_message_repository:
        class: EventSauce\DoctrineMessageRepository\PostgresDoctrineMessageRepository
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@EventSauce\\EventSourcing\\Serialization\\ConstructingMessageSerializer"
            - "identity_user_message"

    EventSauce\EventSourcing\Serialization\ConstructingMessageSerializer: ~
